controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /login

api_refresh_token:
    path: /token/refresh

api_token_invalidate:
    path: /token/invalidate